apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
spec:
  replicas: 1
  selector:
    matchLabels:de
      app: front-node
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: front-node
    spec:
      containers:
      - name: front-pod
        image: dkanunik/barnacle-front:latest
        ports:
        - containerPort: 4201
