apiVersion: apps/v1
kind: Deployment
metadata:
  name: barnacle-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barnacle-front
  template:
    metadata:
      labels:
        app: barnacle-front
    spec:
      containers:
      - name: barnacle-front
        image: dkanunik/barnacle-front:latest
        ports:
        - containerPort: 4200
          protocol: TCP
